name: Build and Upload JAR

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B clean package

      - name: Prepare final JARs
        run: mkdir staging && cp target/*.jar staging/
      - uses: actions/upload-artifact@v4
        with:
          name: YAMLTranslator JAR
          path: staging
